### PR TITLE
Python package

### PR DESCRIPTION
**Pull request by mambocab**
Hey there, @fitnr! I'm the person who owns the Python package you mention [here](https://github.com/dariusk/wordfilter/pull/6). Sorry for the confusion. Here's what happened: I started a Python port, worked with packaging stuff, tried putting the package up on the PyPI test server, then finally saw your PR and bowed out. Since that implementation is up on the test server, it could be taken down at any time.

I was hoping we could work together to get your implementation up on the PyPI production server. I humbly submit this pull request to your branch -- if it looks good to you, then you/we can reopen the PR on the main branch.

You can see the changes I've made in today's (12/21) commits. I've made the following changes:
- merged most recent changes from `master`
- used `any(word in string for word in self.blacklist)` for bad-word checking
- lazily lowercased the blacklist before bad-word checking (see [this bug in the Ruby implementation](https://github.com/dariusk/wordfilter/pull/7))
- made `add_words` "do the right thing" for arbitrary iterables, like `set()`s and generators
- made `add_words` "do the right thing" for strings
- aliased `blacklisted`, `add_words`, and `clear` to the top-level module. This makes things easier in the common case where you only need one blacklist -- the user doesn't have to instantiate a `Wordfilter`. See `test_module_instance` for usage

The end of the commit history gets messy; my apologies.

There are a couple problems:
- the `json` reader seems to be pointed at the wrong file. I've never successfully dealt with datafile management for packages, so I gave up on this one.
- I can't run the tests -- I can't import from the test. Curiously, I can import from the interactive interpreter.

Do you have any insight on these issues?

### CODE REVIEW

**Comment by fitnr** [comment]
Sounds great. I'll come back with more details/answers to your questions after Christmas.

**Comment by mambocab** [comment]
:+1: Merry Christmas to you and yours!

**Comment by fitnr** [comment]
I think I've fixed all the problems you identified. Salient points:
- I merged your commits into a single change (74f32861)
- I fixed the json file-location issue with using `pkg_resources`
- I noticed that in your original repo you had the python library in lib. That seems cleaner, so  I reproduced the change.
- I made the lowercasing less lazy. I could see myself using this library with a very large list, so I guess the laziness seems wasteful.
- There was a typo in the tests. All tests are passing for 2.7.6 and 3.4.2.
- I added a pypandoc converter to covert from md to rst for pypi. This will fail silently if you don't have pypandoc installed on build. This is only an issue for the person uploading to pypi, so pypandoc isn't explicily a dependency anywhere.

My commit is 4db3317c if you want to see my changes in detail. If everything looks good to you, feel free to close this issue and submit a pull request from [dev](https://github.com/fitnr/wordfilter/tree/dev) to dariusk/master (You'd have to fork my dev branch, of course).

**Comment by mambocab** [comment]
I still can't figure out how to install in a way that makes `badwords.json` accessible to `pkg_resources`. It looks like `resource_string` expects the file to be in `site-packages` when installed via `pip install .` and in `lib/wordfilter` when imported locally. Am I doing something wrong in the installation process? I've tried using `pip install .`, `pip install -e .`, and `setup.py develop`.

**Comment by fitnr** [comment]
After much experimentation, I'm having success
- installing with `python setup.py install`
- downloading the tar.gz from test.pypi and runnning `python setup.py install`

I'm not having success:
- installing from test.pypi with pip

I've tried a number of options, including creating a symlink to the json file.

The closest I've come to success with pip is having it install the json file in the site-packages directory. That's reflected in c733345. The json file is accessible from the package with 

``` python
resource_string('wordfilter', '../badwords.json')
```

I don't like having the json file sitting in site_packages, but the only other thing i can think of is a hacky scheme to copy the file to `lib/wordfilter` at build time.

**Comment by fitnr** [comment]
@mambocab thoughts?

**Pull request closed without merging**
