### PR TITLE
Update assert methods

### PR DESCRIPTION
**Pull request by hugovk**

### CODE REVIEW

**Comment by hugovk** [comment]
@fitnr Any thoughts on this?

CPython 2.6 is four years unsupported now, so if it was dropped from here, I could remove the unittest2 stuff from this too.

https://en.m.wikipedia.org/wiki/CPython#Version_history

**Comment by fitnr** [comment]
What problem were these commits meant to address?

**Comment by hugovk** [comment]
When a unit test fails, it gives a more descriptive default error message, and more clearly shows the intent of the test,  which together in general makes it easier to debug and assess the problem.

**Comment by fitnr** [comment]
I understand the general idea of detailed testing method, but for a library this small I don't see the need. I prefer to follow the KISS principle.

**Pull request closed without merging**
